//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CnSharp.VSIX.Yolo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CnSharp.VSIX.Yolo.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string AgentLabel {
            get {
                return ResourceManager.GetString("AgentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Dialog_OK {
            get {
                return ResourceManager.GetString("Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOLO - AI Agents Extender.
        /// </summary>
        public static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent &apos;{0}&apos; configuration not found..
        /// </summary>
        public static string Panel_AgentConfigNotFound {
            get {
                return ResourceManager.GetString("Panel_AgentConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent &apos;{0}&apos; is not installed or not on PATH: {1}.
        /// </summary>
        public static string Panel_AgentNotInstalled {
            get {
                return ResourceManager.GetString("Panel_AgentNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected agent: {0}  (command: {1}).
        /// </summary>
        public static string Panel_AgentSelected {
            get {
                return ResourceManager.GetString("Panel_AgentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Panel_Launch {
            get {
                return ResourceManager.GetString("Panel_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume OFF (R).
        /// </summary>
        public static string Panel_ResumeOff {
            get {
                return ResourceManager.GetString("Panel_ResumeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume ON (R) — agents will resume the last session.
        /// </summary>
        public static string Panel_ResumeOn {
            get {
                return ResourceManager.GetString("Panel_ResumeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume session (R).
        /// </summary>
        public static string Panel_ResumeTooltip {
            get {
                return ResourceManager.GetString("Panel_ResumeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running: {0}  (tab: {1}).
        /// </summary>
        public static string Panel_Running {
            get {
                return ResourceManager.GetString("Panel_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an agent first..
        /// </summary>
        public static string Panel_SelectAgentFirst {
            get {
                return ResourceManager.GetString("Panel_SelectAgentFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open settings dialog..
        /// </summary>
        public static string Panel_SettingsOpenFailed {
            get {
                return ResourceManager.GetString("Panel_SettingsOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        public static string Panel_SettingsSaved {
            get {
                return ResourceManager.GetString("Panel_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Panel_SettingsTooltip {
            get {
                return ResourceManager.GetString("Panel_SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip permissions OFF (Y).
        /// </summary>
        public static string Panel_SkipOff {
            get {
                return ResourceManager.GetString("Panel_SkipOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip permissions ON (Y) — agent permission prompts auto-approved.
        /// </summary>
        public static string Panel_SkipOn {
            get {
                return ResourceManager.GetString("Panel_SkipOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip permissions (Y).
        /// </summary>
        public static string Panel_SkipTooltip {
            get {
                return ResourceManager.GetString("Panel_SkipTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom tool.
        /// </summary>
        public static string Settings_AddCustomTool {
            get {
                return ResourceManager.GetString("Settings_AddCustomTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added a blank custom tool — set its ID, Command and Skip flag, then Validate..
        /// </summary>
        public static string Settings_AddedCustomTool {
            get {
                return ResourceManager.GetString("Settings_AddedCustomTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse….
        /// </summary>
        public static string Settings_Browse {
            get {
                return ResourceManager.GetString("Settings_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove known agent &apos;{0}&apos;..
        /// </summary>
        public static string Settings_CannotRemoveKnownAgent {
            get {
                return ResourceManager.GetString("Settings_CannotRemoveKnownAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose icon for selected tool.
        /// </summary>
        public static string Settings_ChooseIconTitle {
            get {
                return ResourceManager.GetString("Settings_ChooseIconTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base args.
        /// </summary>
        public static string Settings_Col_BaseArgs {
            get {
                return ResourceManager.GetString("Settings_Col_BaseArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Settings_Col_Command {
            get {
                return ResourceManager.GetString("Settings_Col_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string Settings_Col_DisplayName {
            get {
                return ResourceManager.GetString("Settings_Col_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Settings_Col_Icon {
            get {
                return ResourceManager.GetString("Settings_Col_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon path / URL.
        /// </summary>
        public static string Settings_Col_IconPath {
            get {
                return ResourceManager.GetString("Settings_Col_IconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Settings_Col_Id {
            get {
                return ResourceManager.GetString("Settings_Col_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume flag.
        /// </summary>
        public static string Settings_Col_ResumeFlag {
            get {
                return ResourceManager.GetString("Settings_Col_ResumeFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip flag.
        /// </summary>
        public static string Settings_Col_SkipFlag {
            get {
                return ResourceManager.GetString("Settings_Col_SkipFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not found on PATH: {0}.
        /// </summary>
        public static string Settings_CommandNotFoundOnPath {
            get {
                return ResourceManager.GetString("Settings_CommandNotFoundOnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not found on PATH.
        /// </summary>
        public static string Settings_CommandNotFoundTooltip {
            get {
                return ResourceManager.GetString("Settings_CommandNotFoundTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate command: {0}.
        /// </summary>
        public static string Settings_DupCmd {
            get {
                return ResourceManager.GetString("Settings_DupCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate ID: {0}.
        /// </summary>
        public static string Settings_DupId {
            get {
                return ResourceManager.GetString("Settings_DupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not copy icon &apos;{0}&apos; into the YOLO icon folder..
        /// </summary>
        public static string Settings_IconCopyFailed {
            get {
                return ResourceManager.GetString("Settings_IconCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon for selected tool:.
        /// </summary>
        public static string Settings_IconForSelectedTool {
            get {
                return ResourceManager.GetString("Settings_IconForSelectedTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon path is not a valid local file: {0}.
        /// </summary>
        public static string Settings_IconPathInvalid {
            get {
                return ResourceManager.GetString("Settings_IconPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files (*.svg;*.png;*.jpg)|*.svg;*.png;*.jpg|All files (*.*)|*.*.
        /// </summary>
        public static string Settings_ImageFilter {
            get {
                return ResourceManager.GetString("Settings_ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tool to validate..
        /// </summary>
        public static string Settings_NoToolToValidate {
            get {
                return ResourceManager.GetString("Settings_NoToolToValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed selected custom tool..
        /// </summary>
        public static string Settings_RemovedCustomTool {
            get {
                return ResourceManager.GetString("Settings_RemovedCustomTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected.
        /// </summary>
        public static string Settings_RemoveSelected {
            get {
                return ResourceManager.GetString("Settings_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a custom tool row to set its icon. The icon of a known agent cannot be changed..
        /// </summary>
        public static string Settings_SelectCustomToolForIcon {
            get {
                return ResourceManager.GetString("Settings_SelectCustomToolForIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a row to remove..
        /// </summary>
        public static string Settings_SelectRowToRemove {
            get {
                return ResourceManager.GetString("Settings_SelectRowToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Settings_Validate {
            get {
                return ResourceManager.GetString("Settings_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating….
        /// </summary>
        public static string Settings_Validating {
            get {
                return ResourceManager.GetString("Settings_Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation passed..
        /// </summary>
        public static string Settings_ValidationPassed {
            get {
                return ResourceManager.GetString("Settings_ValidationPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Agent extension for Visual Studio.
        /// </summary>
        public static string ToolWindowDescription {
            get {
                return ResourceManager.GetString("ToolWindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOLO.
        /// </summary>
        public static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOLO.
        /// </summary>
        public static string YoloLabel {
            get {
                return ResourceManager.GetString("YoloLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string YoloModeOff {
            get {
                return ResourceManager.GetString("YoloModeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string YoloModeOn {
            get {
                return ResourceManager.GetString("YoloModeOn", resourceCulture);
            }
        }
    }
}
